services:

  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   container_name: api
  #   restart: always
  #   env_file: .env
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file: .env
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: